name: Publish There Windows Git

on:
  push:
    branches:
    - main
    tags-ignore:
    - '*'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Repository Event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MD_GIT_PUBLISH }}
          repository: mhogomchungu/media-downloader-git
          event-type: PublishWindowsGit
